
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CHARLITERAL = 48;
  public static final int LTE = 40;
  public static final int INCREMENT = 30;
  public static final int CHAR = 7;
  public static final int ASSIGNMENT = 36;
  public static final int UMINUS = 51;
  public static final int UPLUS = 50;
  public static final int ROUNDBR_OPEN = 19;
  public static final int INT = 6;
  public static final int MINUS = 35;
  public static final int DECREMENT = 31;
  public static final int FLOATLITERAL = 47;
  public static final int SQRBR_CLOSE = 24;
  public static final int AND = 44;
  public static final int NOT = 29;
  public static final int SEMICOLON = 25;
  public static final int OR = 43;
  public static final int BOOL = 9;
  public static final int COMMA = 26;
  public static final int CLASS = 2;
  public static final int PLUS = 34;
  public static final int MULTIPLY = 32;
  public static final int IF = 14;
  public static final int ID = 45;
  public static final int SQRBR_OPEN = 23;
  public static final int GTS = 38;
  public static final int EOF = 0;
  public static final int RETURN = 5;
  public static final int PRINTLINE = 13;
  public static final int TRUE = 17;
  public static final int error = 1;
  public static final int CURLYBR_CLOSE = 22;
  public static final int VOID = 3;
  public static final int ROUNDBR_CLOSE = 20;
  public static final int EQ = 39;
  public static final int GTE = 41;
  public static final int INTLITERAL = 46;
  public static final int COLON = 28;
  public static final int ELSE = 15;
  public static final int READ = 11;
  public static final int FINAL = 4;
  public static final int WHILE = 16;
  public static final int FLOAT = 10;
  public static final int NE = 42;
  public static final int STRING = 8;
  public static final int QUESTION = 27;
  public static final int STRINGLITERAL = 49;
  public static final int LTS = 37;
  public static final int CURLYBR_OPEN = 21;
  public static final int FALSE = 18;
  public static final int DIVISION = 33;
  public static final int PRINT = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "VOID",
  "FINAL",
  "RETURN",
  "INT",
  "CHAR",
  "STRING",
  "BOOL",
  "FLOAT",
  "READ",
  "PRINT",
  "PRINTLINE",
  "IF",
  "ELSE",
  "WHILE",
  "TRUE",
  "FALSE",
  "ROUNDBR_OPEN",
  "ROUNDBR_CLOSE",
  "CURLYBR_OPEN",
  "CURLYBR_CLOSE",
  "SQRBR_OPEN",
  "SQRBR_CLOSE",
  "SEMICOLON",
  "COMMA",
  "QUESTION",
  "COLON",
  "NOT",
  "INCREMENT",
  "DECREMENT",
  "MULTIPLY",
  "DIVISION",
  "PLUS",
  "MINUS",
  "ASSIGNMENT",
  "LTS",
  "GTS",
  "EQ",
  "LTE",
  "GTE",
  "NE",
  "OR",
  "AND",
  "ID",
  "INTLITERAL",
  "FLOATLITERAL",
  "CHARLITERAL",
  "STRINGLITERAL",
  "UPLUS",
  "UMINUS"
  };
}

